const express = require('express')
const router = express.Router()
const GradeAdminController = require('../Controllers/GradeAdminController.cjs')
const multer = require('multer')

const upload = multer({dest:'upload/'})

router.post('/login',GradeAdminController.login)
router.post('/validateToken',GradeAdminController.validateToken)
router.post('/verifyOTP',GradeAdminController.verifyOTP)
router.post('/getMyGrade',GradeAdminController.getMyGrade)
router.post('/sendLink',GradeAdminController.sendLink)
router.post('/changePassword',GradeAdminController.changePassword)
router.post('/uploadExcel',upload.single('file'),GradeAdminController.uploadExcel)
router.post('/uploadManual',GradeAdminController.uploadManual)
router.get('/getGrades',GradeAdminController.getGrades)
router.post('/addTeacherByExcel',upload.single('file'),GradeAdminController.addTeacherByExcel)
router.post('/addTeacherManually',GradeAdminController.addTeacherManually)
router.post('/addStudentManually',GradeAdminController.addStudentManually)
router.post('/addStudentByExcel',upload.single('file'),GradeAdminController.addStudentByExcel)
router.get('/getSubjects',GradeAdminController.getSubjects)
router.post('/uploadSectionManually',GradeAdminController.uploadSectionManually)
router.post('/uploadSectionByExcel',upload.single('file'),GradeAdminController.uploadSectionByExcel)
router.post('/getSections',GradeAdminController.getSections)
router.post('/getStaff',GradeAdminController.getStaff)
router.post('/addTimeline',GradeAdminController.addTimeline)
router.post('/getTimeline',GradeAdminController.getTimeline)
router.post('/deleteTimeline',GradeAdminController.deleteTimeline)
router.post('/getStaffNames',GradeAdminController.getStaffNames)
router.post('/getCounts',GradeAdminController.getCounts)
router.post('/getOverGrades',GradeAdminController.getOverGrades)
router.post('/getOverSections',GradeAdminController.getOverSections)
router.post('/getOverStudents',GradeAdminController.getOverStudents)
router.post('/getOverSubjects',GradeAdminController.getOverSubjects)
router.post('/getOverTeachers',GradeAdminController.getOverTeachers)
router.get('/logs',GradeAdminController.logs)

module.exports = router