const express = require('express')
const router = express.Router()
const SuperAdminController = require('../Controllers/SuperAdminController.cjs')
const multer = require('multer')
const upload = multer({dest: 'upload/'})

router.post('/loginSuperAdmin',SuperAdminController.login)
router.post('/validateToken',SuperAdminController.validateToken)
router.post('/verifyOTP',SuperAdminController.verifyOTP)
router.post('/sendLink',SuperAdminController.sendLink)
router.post('/changePassword',SuperAdminController.changePassword)
router.post('/uploadExcel',upload.single('file'),SuperAdminController.uploadExcel)
router.post('/uploadManual',SuperAdminController.uploadManual)
router.post('/addGradeManually',SuperAdminController.addGradeManually)
router.post('/addGradeByExcel',upload.single('file'),SuperAdminController.addGradeByExcel)
router.get('/getGrades',SuperAdminController.getGrades)
router.post('/addTeacherManually',SuperAdminController.addTeacherManually)
router.post('/addTeacherByExcel',upload.single('file'),SuperAdminController.addTeacherByExcel)
router.post('/addStudentManually',SuperAdminController.addStudentManually)
router.get('/getSubjects',SuperAdminController.getSubjects)
router.post('/addStudentByExcel',upload.single('file'),SuperAdminController.addStudentByExcel)
router.post('/createGradeAdmin',SuperAdminController.createGradeAdmin)
router.get('/logs',SuperAdminController.logs)
router.post('/retrieveGrades',SuperAdminController.retrieveGrades)
router.get('/getSections',SuperAdminController.getSections)
router.get('/resetAll',SuperAdminController.resetAll)

module.exports = router