on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Code Checkout
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "20.x"
  
      - name: Install dependencies
        run: npm install
        
      - name: Run App
        run: npm test
        working-directory: './school'
        
      - name: Run Build the App
        run: npm run build
        working-directory: './school'
